### ISSUE TITLE
[schéma subventions] champ notificationUE impossible à valider

### ISSUE THREAD

**Issue by joelgombin** [etalab/csv-gg#24]
exemple :

![Capture du 2019-07-18 09-26-19](https://user-images.githubusercontent.com/1918735/61437808-414ad300-a93e-11e9-8a65-6fbb871812cd.png)

**Comment by AntoineAugusti** [comment]
Merci pour ce report de bug ! La PR #25 corrige le problème plus général. Dès que ce sera mergé ce sera corrigé.

**Comment by joelgombin** [comment]
Super !
