### ISSUE TITLE
Support Markdown in field descriptions

### ISSUE THREAD

**Issue by risseraka** [etalab/csv-gg#32]
There seems to be a formatting issue with what looks like Markdown, not properly displaying a link.

Example: https://csv-gg.etalab.studio/?schema=scdl%2Fequipements
```
Les entrées de la [nomenclature des équipements collectifs publics](https://docs.google.com/spreadsheets/d/157WPWMUDC6w58Aep1dgWzzunKEjzSd-QmyuEHa8RFqc) sont divisées en 10 grandes familles. 
```

Cheers.

**Comment by abulte** [comment]
Thanks!

**Comment by AntoineAugusti** [comment]
Is it something we should do? The Table Schema spec doesn't say that descriptions could be written in Markdown.

Do we push this?

**Comment by abulte** [comment]
True. I guess we can be smart and lenient about this, even w/o proposing a change to the spec. Try to parse as Markdown and if it fails fallback to text.

Or create issues in all SCDL schemas ;-)

**Comment by abulte** [comment]
What do @johanricher and @cbenz think about this? Maybe you already proposed a change to the spec?

**Comment by johanricher** [comment]
Well it was just a logical progression from our point of view. Once we displayed the descriptions in a [UI](https://go.validata.fr/) and within [documentation](https://scdl.opendatafrance.net/docs/), users (@OpenDataFrance) wanted links in the descriptions. So put them in, in the way that seemed to make the most sense. Also, Markdown seem to be encouraged in the [TS spec](https://frictionlessdata.io/schemas/table-schema.json) but I can't remember if that actually made a difference in our choice.

If needed @cbenz and @pierredittgen could go into details on how we managed the Markdown parsing and rendering with [Validata](https://git.opendatafrance.net/validata/validata-ui) and [SCDL documentation](https://git.opendatafrance.net/scdl/documentation) (i.e. [table-schema-to-markdown](https://framagit.org/opendataschema/table-schema-to-markdown)).

**Comment by AntoineAugusti** [comment]
I'll code this feature

**Comment by risseraka** [comment]
Pretty sweet!
Cheers,
